version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: de-mvp
    ports:
      - "8000:8000"  # Map container's port 8000 to host's port 8000
    env_file:
      - .env  # Load environment variables from an .env file
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
